clientID = "6zu1kT3jVrKwGzI3wI1nXQ"
clientSecret= "eBTr0C4gNcOJZs3mzp7DdGvCgjhohw"
userAgent = "script:StockScraper:1.0 (by u/Database_External)"
_username = "Database-External"
_password = "peanutz831"